<a href="https://www.kaggle.com/code/kyeongsupchoi/model3?scriptVersionId=129851577" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# 프로젝트 소개
* [프로젝트 소개](#introduction)
* [1 단계: 탐색적 데이터 분석](#step-one)
* [2 단계: 모델 학습](#step-two)
* [3 단계: 모델 검증](#step-three)

In [1]:
import pandas as pd
from sklearn.neighbors import LocalOutlierFactor
import sys
import numpy

<a id="step-one"></a>
# **1 단계: 탐색적 데이터 분석**

In [2]:
df = pd.read_csv("/kaggle/input/insurance/insurance.csv")

X = df[['age', 'bmi', 'children', 'charges']]

X

      age     bmi  children      charges
0      19  27.900         0  16884.92400
1      18  33.770         1   1725.55230
2      28  33.000         3   4449.46200
3      33  22.705         0  21984.47061
4      32  28.880         0   3866.85520
...   ...     ...       ...          ...
1333   50  30.970         3  10600.54830
1334   18  31.920         0   2205.98080
1335   18  36.850         0   1629.83350
1336   21  25.800         0   2007.94500
1337   61  29.070         0  29141.36030

[1338 rows x 4 columns]

<a id="step-two"></a>
# **2 단계: 모델 학습**
Train the initial model

In [3]:
clf = LocalOutlierFactor(n_neighbors=20, contamination=0.1)
# use fit_predict to compute the predicted labels of the training samples
# (when LOF is used for outlier detection, the estimator has no predict,
# decision_function and score_samples methods).
y_pred = clf.fit_predict(X)
y = pd.DataFrame(y_pred, columns=['outlier'])
y

      outlier
0           1
1           1
2           1
3           1
4           1
...       ...
1333        1
1334        1
1335        1
1336        1
1337        1

[1338 rows x 1 columns]

In [4]:
z = pd.concat([X, y], axis = 1)

<a id="step-three"></a>
# **3 단계: 모델 검증**

In [5]:
z.loc[z['outlier'] == -1]

      age     bmi  children      charges  outlier
12     23  34.400         0   1826.84300       -1
15     19  24.600         1   1837.23700       -1
22     18  34.100         0   1137.01100       -1
34     28  36.400         1  51194.55914       -1
37     26  20.800         0   2302.30000       -1
...   ...     ...       ...          ...      ...
1292   21  23.210         0   1515.34490       -1
1300   45  30.360         0  62592.87309       -1
1317   18  53.130         0   1163.46270       -1
1324   31  25.935         1   4239.89265       -1
1326   42  32.870         0   7050.02130       -1

[134 rows x 5 columns]